'use strict';

const BUILD='AP-800';
const DB_NAME='arise-player-v3';
const STORE='tracks';
const K={session:'arise.ap800.session',favorites:'arise.ap800.favorites',recent:'arise.ap800.recent',playlists:'arise.ap800.playlists',sort:'arise.ap800.sort'};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const audio=$('#audio');
let db=null,tracks=[],view='home',search='',edit=false,activePlaylist=null,toastTimer=null,lastSessionWrite=0;
const state={current:null,queue:[],index:-1,url:null,shuffle:false,repeat:'off',resumeAt:0,transitioning:false,seeking:false,sleepTimer:null,sleepEnds:0};

function read(k,f){try{const v=localStorage.getItem(k);return v==null?f:JSON.parse(v)}catch{return f}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
function uid(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`}
function clean(v){return String(v??'').replace(/\0/g,'').replace(/\s+/g,' ').trim()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(s){s=Math.max(0,Math.floor(Number(s)||0));return`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function parseName(name=''){const raw=String(name).replace(/\.[^.]+$/,'').replace(/_+/g,' ').trim();const p=raw.split(/\s+-\s+/);return p.length>1?{artist:p.shift().trim()||'Unknown Artist',title:p.join(' - ').trim()||raw}:{artist:'Unknown Artist',title:raw||'Untitled track'}}
function title(t){return clean(t?.title)||parseName(t?.filename).title}
function artist(t){return clean(t?.artist)||'Unknown Artist'}
function mime(t){return clean(t?.mimeType)||'application/octet-stream'}
function bytesToBlob(t){if(!t)return null;const raw=t.audioBytes;if(raw instanceof ArrayBuffer)return new Blob([raw],{type:mime(t)});if(ArrayBuffer.isView(raw))return new Blob([raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.byteLength)],{type:mime(t)});return t.blob instanceof Blob?t.blob:null}
function toast(msg){const el=$('#toast');clearTimeout(toastTimer);el.textContent=msg;el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),1800)}

async function openDB(){if(db)return db;db=await new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return db}
async function refresh(){const d=await openDB();tracks=await new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readonly'),r=tx.objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)});return tracks}
async function put(t){const d=await openDB();return new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readwrite'),r=tx.objectStore(STORE).put(t);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function del(id){const d=await openDB();return new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}

function favorites(){const x=read(K.favorites,[]);return Array.isArray(x)?x:[]}
function isFav(t){return favorites().includes(t.id)}
function setFav(t,on){let a=favorites().filter(x=>x!==t.id);if(on)a.unshift(t.id);write(K.favorites,a);renderAll()}
function recent(){const x=read(K.recent,[]);return Array.isArray(x)?x:[]}
function noteRecent(t){let a=recent().filter(x=>x!==t.id);a.unshift(t.id);write(K.recent,a.slice(0,50))}
function playlists(){const x=read(K.playlists,[]);return Array.isArray(x)?x:[]}
function savePlaylists(x){write(K.playlists,x)}
function byId(id){return tracks.find(t=>t.id===id)||null}
function queueFromIds(ids){return ids.map(byId).filter(Boolean)}
function defaultQueue(){const s=read(K.sort,'recent'),a=tracks.slice();if(s==='title')a.sort((x,y)=>title(x).localeCompare(title(y)));else if(s==='artist')a.sort((x,y)=>artist(x).localeCompare(artist(y))||title(x).localeCompare(title(y)));else a.sort((x,y)=>(y.addedAt||0)-(x.addedAt||0));return a}
function visible(){const q=search.trim().toLowerCase();return defaultQueue().filter(t=>!q||title(t).toLowerCase().includes(q)||artist(t).toLowerCase().includes(q))}
function coverData(t){if(t?.artworkData)return t.artworkData;const initials=title(t).split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'A';const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#29292d"/><stop offset="1" stop-color="#08080a"/></linearGradient></defs><rect width="600" height="600" rx="50" fill="url(#g)"/><text x="300" y="330" text-anchor="middle" font-family="system-ui" font-size="150" font-weight="800" fill="white">${esc(initials)}</text></svg>`;return`data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`}
function setArt(el,t){if(!el)return;el.innerHTML='';const img=new Image();img.src=coverData(t);img.alt='';img.decoding='async';img.onerror=()=>{el.innerHTML=`<div class="fallback">${esc((title(t)[0]||'A').toUpperCase())}</div>`};el.appendChild(img)}
function quality(t){const n=clean(t?.filename),ext=(n.split('.').pop()||'AUDIO').toUpperCase();if(['FLAC','WAV','AIFF','AIF'].includes(ext))return`LOSSLESS • ${ext}`;const b=t?.audioBytes?.byteLength||0,d=Number(t?.duration)||0;if(b&&d>1)return`≈${Math.round((b*8/d/1000)/8)*8} KBPS • ${ext}`;return`SOURCE • ${ext}`}

function release(){try{audio.pause();audio.removeAttribute('src');audio.load()}catch{}if(state.url){try{URL.revokeObjectURL(state.url)}catch{}state.url=null}}
function setQueue(q,t){state.queue=q.filter(Boolean);let i=state.queue.findIndex(x=>x.id===t.id);if(i<0){state.queue.unshift(t);i=0}state.index=i}
function nextItem(){if(!state.queue.length)return null;if(state.shuffle&&state.queue.length>1){let i=state.index;while(i===state.index)i=Math.floor(Math.random()*state.queue.length);return state.queue[i]}const n=state.index+1;if(n<state.queue.length)return state.queue[n];return state.repeat==='all'?state.queue[0]:null}
function prevItem(){if(!state.queue.length)return null;const p=state.index-1;if(p>=0)return state.queue[p];return state.repeat==='all'?state.queue[state.queue.length-1]:state.queue[0]||null}
function saveSession(force=false){if(!state.current)return;const now=Date.now();if(!force&&now-lastSessionWrite<1800)return;lastSessionWrite=now;write(K.session,{id:state.current.id,at:audio.currentTime||state.resumeAt||0,queue:state.queue.map(x=>x.id),index:state.index,ts:now})}
async function playCurrent({at=0,autoplay=true}={}){const t=state.current,b=bytesToBlob(t);if(!t||!b){toast('This file is unavailable');return false}release();state.url=URL.createObjectURL(b);audio.src=state.url;audio.preload='metadata';audio.playbackRate=1;audio.defaultPlaybackRate=1;syncMetadata();const seek=()=>{if(at>0&&Number.isFinite(audio.duration))audio.currentTime=Math.min(at,Math.max(0,audio.duration-.05));syncPosition(true)};audio.addEventListener('loadedmetadata',seek,{once:true});try{audio.load()}catch{}renderPlayer();saveSession(true);if(autoplay){try{await audio.play();return true}catch(e){console.debug('play failed',e);toast('Tap play once to start audio')}}return false}
async function playTrack(t,q=defaultQueue(),at=0){if(!t)return;state.current=t;setQueue(q,t);state.resumeAt=0;await playCurrent({at,autoplay:true})}
async function nextTrack(){if(state.transitioning)return;const n=nextItem();if(!n){audio.pause();return}state.transitioning=true;state.current=n;state.index=state.queue.findIndex(x=>x.id===n.id);await playCurrent({at:0,autoplay:true});state.transitioning=false}
async function previousTrack(){if(Number(audio.currentTime)>3.5){audio.currentTime=0;syncPosition(true);return}const p=prevItem();if(!p)return;state.current=p;state.index=state.queue.findIndex(x=>x.id===p.id);await playCurrent({at:0,autoplay:true})}
async function resilientPlay(){if(!state.current)return;try{if(audio.src){await audio.play();return}}catch{}const at=Number(audio.currentTime)||Number(state.resumeAt)||Number(read(K.session,{at:0}).at)||0;await playCurrent({at,autoplay:true})}
function toggle(){if(!state.current){const q=defaultQueue();if(q[0])playTrack(q[0],q);return}audio.paused?resilientPlay():audio.pause()}

function mediaHandlers(){if(!('mediaSession'in navigator))return;const set=(n,f)=>{try{navigator.mediaSession.setActionHandler(n,f)}catch{}};set('play',resilientPlay);set('pause',()=>{audio.pause();saveSession(true)});set('previoustrack',previousTrack);set('nexttrack',nextTrack);set('seekbackward',null);set('seekforward',null);set('seekto',d=>{if(Number.isFinite(d?.seekTime)&&Number.isFinite(audio.duration)){audio.currentTime=Math.max(0,Math.min(audio.duration,d.seekTime));syncPosition(true)}})}
function syncMetadata(){if(!state.current||!('mediaSession'in navigator))return;try{navigator.mediaSession.metadata=new MediaMetadata({title:title(state.current),artist:artist(state.current),album:'Arise Player',artwork:[{src:coverData(state.current),sizes:'600x600'}]})}catch{}}
let posAt=0;function syncPosition(force=false){if(typeof navigator.mediaSession?.setPositionState!=='function')return;const now=Date.now();if(!force&&now-posAt<700)return;posAt=now;const d=Number(audio.duration),p=Number(audio.currentTime);if(!Number.isFinite(d)||d<=0||!Number.isFinite(p))return;try{navigator.mediaSession.setPositionState({duration:d,position:Math.max(0,Math.min(d,p)),playbackRate:1})}catch{}}

async function detachFile(file){if(!file||typeof file.arrayBuffer!=='function')throw new Error('Unreadable file');const audioBytes=await file.arrayBuffer();return{audioBytes,mimeType:file.type||'application/octet-stream'}}
function durationOf(blob){return new Promise(resolve=>{let done=false,url=URL.createObjectURL(blob),a=document.createElement('audio'),finish=v=>{if(done)return;done=true;clearTimeout(timer);try{URL.revokeObjectURL(url)}catch{}resolve(Number.isFinite(v)?v:0)};a.preload='metadata';a.onloadedmetadata=()=>finish(a.duration);a.onerror=()=>finish(0);a.src=url;const timer=setTimeout(()=>finish(0),3500)})}
async function importFiles(files,input){const list=Array.from(files||[]).filter(f=>f&&typeof f.arrayBuffer==='function'&&Number(f.size)>=0);if(!list.length)return;toast(`Importing ${list.length} track${list.length===1?'':'s'}…`);let n=0;for(const file of list){try{const detached=await detachFile(file),blob=new Blob([detached.audioBytes],{type:detached.mimeType}),d=await durationOf(blob),p=parseName(file.name),t={id:uid(),title:p.title,artist:p.artist,filename:file.name||'audio',mimeType:detached.mimeType,audioBytes:detached.audioBytes,duration:d,addedAt:Date.now()+n};await put(t);n++}catch(e){console.error('import failed',e)}}try{input.value=''}catch{}await refresh();renderAll();try{await navigator.storage?.persist?.()}catch{}toast(n===list.length?`${n} track${n===1?'':'s'} imported`:`Imported ${n} of ${list.length}`)}

function go(v){view=v;$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===v));window.scrollTo(0,0);if(v==='library')renderLibrary();if(v==='playlists')renderPlaylists();if(v==='more')renderMore()}
function trackRow(t,q=visible(),playlist=null){const row=document.createElement('div');row.className=`track${edit?' edit':''}`;const a=document.createElement('div');a.className='trackArt';setArt(a,t);const c=document.createElement('div');c.className='trackCopy';c.innerHTML=`<b>${esc(title(t))}</b><small>${esc(artist(t))}</small>`;row.append(a,c);if(edit){const d=document.createElement('button');d.className='deleteBtn';d.textContent='Delete';d.onclick=e=>{e.stopPropagation();deleteTrack(t)};row.appendChild(d)}else{const m=document.createElement('button');m.className='menuBtn';m.textContent='•••';m.onclick=e=>{e.stopPropagation();openTrackMenu(t,playlist)};row.appendChild(m)}row.onclick=()=>{if(!edit)playTrack(t,q)};if(state.current?.id===t.id){const i=document.createElement('i');i.className='playingDot';i.textContent=audio.paused?'•':'▶';row.appendChild(i)}return row}
function renderLibrary(){const arr=visible(),root=$('#libraryList');root.innerHTML='';$('#libraryCount').textContent=`${tracks.length} track${tracks.length===1?'':'s'} • stored locally`;$('#libraryTools').hidden=!tracks.length;$('#emptyLibrary').hidden=!!tracks.length;$('#sortBtn').textContent=({recent:'Recent',title:'Title',artist:'Artist'})[read(K.sort,'recent')];$('#editBtn').textContent=edit?'Done':'Edit';$('#editBtn').classList.toggle('active',edit);for(const t of arr)root.appendChild(trackRow(t,arr));if(tracks.length&&!arr.length)root.innerHTML='<div class="empty"><h2>No matches.</h2><p>Try another title or artist.</p></div>'}
function renderHome(){const f=favorites().filter(byId).length;$('#heroCopy').textContent=tracks.length?`${tracks.length} local tracks. No account. Ready offline.`:'Import a few songs and Arise becomes yours.';$('#heroStats').innerHTML=`<span class="pill"><b>${tracks.length}</b> tracks</span><span class="pill"><b>${f}</b> favorites</span><span class="pill"><b>${BUILD}</b> build</span>`;const s=read(K.session,null),t=s&&byId(s.id);$('#continueSection').hidden=!t;if(t){const b=$('#continueCard');b.innerHTML='';const a=document.createElement('div');a.className='trackArt';setArt(a,t);const c=document.createElement('div');c.className='trackCopy';c.innerHTML=`<b>${esc(title(t))}</b><small>${esc(artist(t))} • ${fmt(s.at)}</small>`;const p=document.createElement('span');p.className='miniPlay';b.append(a,c,p);b.onclick=()=>playTrack(t,Array.isArray(s.queue)?queueFromIds(s.queue):defaultQueue(),s.at||0)}const rec=queueFromIds(recent()).slice(0,10),strip=$('#recentStrip');strip.innerHTML='';$('#recentSection').hidden=!rec.length;for(const t of rec){const b=document.createElement('button');b.className='recent';const a=document.createElement('div');a.className='art';setArt(a,t);const c=document.createElement('div');c.innerHTML=`<b>${esc(title(t))}</b><small>${esc(artist(t))}</small>`;b.append(a,c);b.onclick=()=>playTrack(t,rec);strip.appendChild(b)}}
function renderPlaylists(){const root=$('#playlistRoot'),pls=playlists();root.innerHTML='';if(activePlaylist){const p=pls.find(x=>x.id===activePlaylist);if(!p){activePlaylist=null;return renderPlaylists()}const q=queueFromIds(p.tracks||[]);const h=document.createElement('div');h.className='sectionHead';h.innerHTML=`<div><button id="backPl" class="tool">‹ Playlists</button><h2 style="margin:10px 0 2px;font-size:32px">${esc(p.name)}</h2><p style="color:var(--muted);margin:0">${q.length} tracks</p></div><button id="delPl" class="tool">Delete</button>`;root.appendChild(h);const l=document.createElement('div');l.className='trackList';q.forEach(t=>l.appendChild(trackRow(t,q,p)));if(!q.length)l.innerHTML='<div class="empty"><h2>Nothing here yet.</h2><p>Add songs from their ••• menu.</p></div>';root.appendChild(l);$('#backPl').onclick=()=>{activePlaylist=null;renderPlaylists()};$('#delPl').onclick=()=>{if(confirm(`Delete “${p.name}”?\n\nSongs stay in your library.`)){savePlaylists(pls.filter(x=>x.id!==p.id));activePlaylist=null;renderPlaylists()}};return}if(!pls.length){root.innerHTML='<div class="empty"><div class="emptyMark">≡</div><h2>No playlists yet.</h2><p>Create one, then add songs from their ••• menu.</p></div>';return}const g=document.createElement('div');g.className='playlistGrid';for(const p of pls){const b=document.createElement('button');b.className='playlist';const cover=document.createElement('div');cover.className='playlistCover';const q=queueFromIds(p.tracks||[]);for(let i=0;i<4;i++){const x=document.createElement('div');if(q[i])setArt(x,q[i]);cover.appendChild(x)}const c=document.createElement('div');c.innerHTML=`<b>${esc(p.name)}</b><small>${q.length} tracks</small>`;b.append(cover,c);b.onclick=()=>{activePlaylist=p.id;renderPlaylists()};g.appendChild(b)}root.appendChild(g)}
async function renderMore(){const f=favorites().filter(byId);$('#favoritesCount').textContent=`${f.length} track${f.length===1?'':'s'}`;$('#sleepStatus').textContent=state.sleepEnds?`${Math.max(1,Math.ceil((state.sleepEnds-Date.now())/60000))} min`:'Off';const music=tracks.reduce((n,t)=>n+(t.audioBytes?.byteLength||0),0);$('#storageText').textContent=music>1048576?`${(music/1048576).toFixed(1)} MB local`:`${Math.round(music/1024)} KB local`;$('#buildState').textContent=`GitHub Pages edition • ${location.host}`}
function renderAll(){renderLibrary();renderHome();renderPlaylists();renderMore();renderPlayer()}
function renderPlayer(){const t=state.current;$('#mini').hidden=!t;$('#app').classList.toggle('hasMini',!!t);if(!t)return;setArt($('#miniArt'),t);setArt($('#nowArt'),t);$('#miniTitle').textContent=title(t);$('#miniArtist').textContent=artist(t);$('#nowTitle').textContent=title(t);$('#nowArtist').textContent=artist(t);$('#heart').textContent=isFav(t)?'♥':'♡';$('#heart').classList.toggle('active',isFav(t));$('#miniPlay').classList.toggle('playing',!audio.paused);$('#play').classList.toggle('playing',!audio.paused);$('#quality').textContent=quality(t);$('#queuePos').textContent=state.queue.length?`${state.index+1} of ${state.queue.length}`:'1 of 1';const n=nextItem();$('#upNext').hidden=!n;if(n){$('#upTitle').textContent=title(n);$('#upArtist').textContent=artist(n)}$('#backdrop').style.backgroundImage=`url("${coverData(t).replace(/"/g,'&quot;')}")`;updateTimeline();syncMetadata()}
function updateTimeline(){if(!state.current)return;const d=Number(audio.duration)||0,p=Number(audio.currentTime)||0;if(!state.seeking)$('#seek').value=d?Math.round(p/d*1000):0;$('#elapsed').textContent=fmt(p);$('#remaining').textContent=`−${fmt(Math.max(0,d-p))}`;$('#miniProgress').style.setProperty('--progress',d?`${Math.min(100,p/d*100)}%`:'0%')}

function openSheet(html){const d=$('#sheet');$('#sheetBody').innerHTML=html;try{d.showModal()}catch{d.setAttribute('open','')}}
function closeSheet(){const d=$('#sheet');try{d.close()}catch{d.removeAttribute('open')}}
function openTrackMenu(t,pl=null){$('#sheet')._track=t;$('#sheet')._pl=pl;const pls=playlists();openSheet(`<div class="sheetTitle"><h3>${esc(title(t))}</h3><p>${esc(artist(t))}</p></div><button class="sheetOption" data-act="fav"><span>${isFav(t)?'Remove from favorites':'Add to favorites'}</span><span>${isFav(t)?'♥':'♡'}</span></button>${pls.map(p=>`<button class="sheetOption" data-add="${esc(p.id)}"><span>Add to ${esc(p.name)}</span><span>＋</span></button>`).join('')}${pl?`<button class="sheetOption" data-remove="${esc(pl.id)}"><span>Remove from ${esc(pl.name)}</span><span>−</span></button>`:''}<button class="sheetOption danger" data-act="delete"><span>Delete from library</span><span>×</span></button>`)}
async function deleteTrack(t){closeSheet();if(!confirm(`Delete “${title(t)}” from Arise Player?\n\nThis removes the local audio file.`))return;const was=state.current?.id===t.id;await del(t.id);let pls=playlists();pls.forEach(p=>p.tracks=(p.tracks||[]).filter(id=>id!==t.id));savePlaylists(pls);write(K.favorites,favorites().filter(id=>id!==t.id));write(K.recent,recent().filter(id=>id!==t.id));if(was){release();state.current=null;state.queue=[];state.index=-1;localStorage.removeItem(K.session)}await refresh();renderAll();toast('Song deleted')}
function newPlaylist(){const d=$('#formDialog'),f=$('#formBody');f.innerHTML='<div class="formWrap"><h3>New playlist</h3><input id="plName" class="field" placeholder="Playlist name" maxlength="50"><div class="dialogActions"><button value="cancel">Cancel</button><button value="save" class="confirm">Save</button></div></div>';f.onsubmit=e=>{e.preventDefault();if(e.submitter?.value==='cancel'){d.close();return}const n=clean($('#plName').value);if(!n)return;const a=playlists();a.unshift({id:uid(),name:n,tracks:[]});savePlaylists(a);d.close();renderPlaylists()};try{d.showModal()}catch{d.setAttribute('open','')}}

function bind(){
  $$('.tab').forEach(b=>b.onclick=()=>go(b.dataset.tab));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#brandHome').onclick=()=>go('home');$('#openSettings').onclick=()=>go('more');
  const bindImport=id=>{const input=$(id);input.addEventListener('change',()=>importFiles(input.files,input))};bindImport('#importTop');bindImport('#importEmpty');
  $('#search').oninput=e=>{search=e.target.value;renderLibrary()};$('#sortBtn').onclick=()=>{const s=read(K.sort,'recent'),n=s==='recent'?'title':s==='title'?'artist':'recent';write(K.sort,n);renderLibrary()};$('#editBtn').onclick=()=>{edit=!edit;renderLibrary()};$('#newPlaylist').onclick=newPlaylist;
  $$('[data-mix]').forEach(b=>b.onclick=()=>{let q=b.dataset.mix==='favorites'?queueFromIds(favorites()):defaultQueue();if(b.dataset.mix==='shuffle'){q=q.slice().sort(()=>Math.random()-.5)}if(q[0])playTrack(q[0],q);else toast('Import some music first')});
  $('#mini').onclick=e=>{if(e.target.closest('#miniPlay')){e.stopPropagation();toggle()}else{$('#now').hidden=false;document.body.style.overflow='hidden';renderPlayer()}};$('#closeNow').onclick=()=>{$('#now').hidden=true;document.body.style.removeProperty('overflow')};$('#play').onclick=toggle;$('#prev').onclick=previousTrack;$('#next').onclick=nextTrack;$('#heart').onclick=()=>state.current&&setFav(state.current,!isFav(state.current));$('#shuffle').onclick=()=>{state.shuffle=!state.shuffle;$('#shuffle').classList.toggle('active',state.shuffle);toast(state.shuffle?'Shuffle on':'Shuffle off')};$('#repeat').onclick=()=>{state.repeat=state.repeat==='off'?'all':state.repeat==='all'?'one':'off';$('#repeat').classList.toggle('active',state.repeat!=='off');$('#repeat').textContent=state.repeat==='one'?'↻¹':'↻'};$('#trackMenu').onclick=()=>state.current&&openTrackMenu(state.current);
  const seek=$('#seek');seek.onpointerdown=()=>state.seeking=true;seek.oninput=()=>{const d=Number(audio.duration)||0,p=d*Number(seek.value)/1000;$('#elapsed').textContent=fmt(p);$('#remaining').textContent=`−${fmt(Math.max(0,d-p))}`};seek.onchange=()=>{const d=Number(audio.duration)||0;if(d)audio.currentTime=d*Number(seek.value)/1000;state.seeking=false;syncPosition(true)};
  $('#favoritesBtn').onclick=()=>{const q=queueFromIds(favorites());q[0]?playTrack(q[0],q):toast('No favorites yet')};$('#sleepBtn').onclick=()=>{const m=prompt('Sleep timer in minutes (0 to cancel):','30');if(m==null)return;const n=Math.max(0,Number(m)||0);clearTimeout(state.sleepTimer);state.sleepEnds=0;if(!n){renderMore();toast('Sleep timer off');return}state.sleepEnds=Date.now()+n*60000;state.sleepTimer=setTimeout(()=>{audio.pause();state.sleepEnds=0;renderMore()},n*60000);renderMore();toast(`Sleep timer: ${n} min`)};$('#clearHistory').onclick=()=>{if(confirm('Clear recent listening history?\n\nSongs and playlists stay.')){write(K.recent,[]);renderAll();toast('History cleared')}};$('#storageBtn').onclick=async()=>{try{const ok=await navigator.storage?.persist?.();toast(ok?'Offline storage protected':'Storage policy unchanged')}catch{toast('Storage request unavailable')}};
  $('#sheet').onclick=e=>{if(e.target===$('#sheet')){closeSheet();return}const b=e.target.closest('button'),t=$('#sheet')._track;if(!b||!t)return;if(b.dataset.act==='fav'){setFav(t,!isFav(t));closeSheet()}else if(b.dataset.act==='delete')deleteTrack(t);else if(b.dataset.add){const a=playlists(),p=a.find(x=>x.id===b.dataset.add);if(p&&!p.tracks.includes(t.id))p.tracks.push(t.id);savePlaylists(a);closeSheet();renderPlaylists();toast(`Added to ${p?.name||'playlist'}`)}else if(b.dataset.remove){const a=playlists(),p=a.find(x=>x.id===b.dataset.remove);if(p)p.tracks=(p.tracks||[]).filter(id=>id!==t.id);savePlaylists(a);closeSheet();renderPlaylists();toast('Removed from playlist')}};
  audio.addEventListener('play',()=>{mediaHandlers();try{navigator.mediaSession.playbackState='playing'}catch{}if(state.current)noteRecent(state.current);renderAll()});audio.addEventListener('pause',()=>{try{navigator.mediaSession.playbackState='paused'}catch{}saveSession(true);renderAll()});audio.addEventListener('loadedmetadata',()=>{mediaHandlers();syncPosition(true);renderPlayer()});audio.addEventListener('timeupdate',()=>{updateTimeline();saveSession();syncPosition()});audio.addEventListener('ended',async()=>{if(state.repeat==='one'){audio.currentTime=0;await resilientPlay()}else await nextTrack()});audio.addEventListener('playing',mediaHandlers);audio.addEventListener('ratechange',()=>{if(Math.abs(audio.playbackRate-1)>.001)audio.playbackRate=1});
  document.addEventListener('visibilitychange',()=>{if(!document.hidden){mediaHandlers();syncMetadata();syncPosition(true)}});window.addEventListener('pageshow',()=>{mediaHandlers();syncMetadata();syncPosition(true)});window.addEventListener('beforeunload',()=>{saveSession(true);if(state.url)try{URL.revokeObjectURL(state.url)}catch{}});
}

async function restoreSession(){const s=read(K.session,null);if(!s||Date.now()-Number(s.ts||0)>2592000000)return;const t=byId(s.id);if(!t)return;state.current=t;state.resumeAt=Number(s.at)||0;setQueue(Array.isArray(s.queue)&&s.queue.length?queueFromIds(s.queue):defaultQueue(),t);renderPlayer();syncMetadata()}
async function registerSW(){if(!('serviceWorker'in navigator))return;try{const r=await navigator.serviceWorker.register('./sw.js?v=800',{scope:'./'});r.update().catch(()=>{})}catch(e){console.debug('sw unavailable',e)}}
async function init(){bind();mediaHandlers();go('home');await openDB();await refresh();await restoreSession();renderAll();registerSW();console.info(`Arise Player ${BUILD}`)}
init().catch(e=>{console.error(e);document.body.innerHTML=`<main style="padding:40px;color:white"><h1>Arise Player could not start.</h1><p>${esc(e?.message||String(e))}</p></main>`});
